module.exports = {
  preset: '@react-native/jest-preset',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  coverageReporters: ['text', 'lcov', 'json-summary'],
  collectCoverageFrom: [
    'src/App.tsx',
    'src/components/{Badge,BottomSheet,Button,Card,EmptyState,ErrorBoundary,FAB,FilterBottomSheet,Hint,Input,NetworkToast,ObservationListItem,ObservationSkeleton,ObservationUndoToast,ScreenContainer,Skeleton,SwipeableObservationItem,SyncStatusIcon}/*.tsx',
    '!src/components/**/*.stories.tsx',
    'src/scenes/ObservationFormScreen/ObservationFormScreen.tsx',
    'src/scenes/ObservationFormScreen/useObservationFormViewModel.ts',
    'src/scenes/ObservationsScreen/ObservationsScreen.tsx',
    'src/scenes/ObservationsScreen/useObservationsViewModel.ts',
    'src/scenes/SettingsScreen/SettingsScreen.tsx',
    'src/store/observations/slice.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  moduleNameMapper: {
    '^@test-utils$': '<rootDir>/src/__tests__/testUtils',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@providers/(.*)$': '<rootDir>/src/providers/$1',
    '^@scenes/(.*)$': '<rootDir>/src/scenes/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@storage/(.*)$': '<rootDir>/src/storage/$1',
    '^@store/(.*)$': '<rootDir>/src/store/$1',
    '^@theme/(.*)$': '<rootDir>/src/theme/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
  modulePathIgnorePatterns: ['<rootDir>/.claude/'],
  testMatch: ['**/?(*.)+(test).[tj]s?(x)'],
  testPathIgnorePatterns: ['<rootDir>/.claude/'],
  watchman: false,
  openHandlesTimeout: 0,
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native|@react-navigation|@react-native-community|react-native-safe-area-context|react-redux|@reduxjs/toolkit|redux-saga|styled-components|react-native-mmkv|react-native-nitro-modules|immer|react-native-vector-icons|react-native-config|@react-native-firebase)/)',
  ],
};
