/* do not change this file, it is auto generated by storybook. */
/* To regenerate run: yarn storybook:generate */

import {start, updateView} from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-backgrounds/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: '../src',
    files: '**/*.stories.?(ts|tsx|js|jsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-ignore — require.context is a Metro bundler feature (enabled via metro.config.js)
    req: require.context(
      '../src',
      true,
      /\.stories\.(ts|tsx|js|jsx)$/,
    ),
  },
];

declare global {
  // eslint-disable-next-line no-var
  var view: ReturnType<typeof start>;
  // eslint-disable-next-line no-var
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require('./preview'),
  require('@storybook/react-native/preview'),
  require('@storybook/addon-actions/preview'),
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view = global.view;
