/* eslint-disable @typescript-eslint/no-require-imports */
/* do not change this file, it is auto generated by storybook. */
/* To regenerate run: yarn storybook:generate */

import {start, updateView} from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-backgrounds/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: '../src',
    files: '**/*.stories.?(ts|tsx|js|jsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-expect-error require.context is provided by Metro when enabled in metro.config.js
    req: require.context(
      '../src',
      true,
      /\.stories\.(ts|tsx|js|jsx)$/,
    ),
  },
];

declare global {
  var view: ReturnType<typeof start> | undefined;
  var STORIES: typeof normalizedStories | undefined;
}

const annotations = [
  require('./preview'),
  require('@storybook/react-native/preview'),
  require('@storybook/addon-actions/preview'),
];

globalThis.STORIES = normalizedStories;

// @ts-expect-error hot is injected by Metro in development
module?.hot?.accept?.();

if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view = globalThis.view;
